name: Deploy React + Vite to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Deploy to GitHub Pages
        run: |
          git config --global user.name 'anuragrokade'
          git config --global user.email 'anuragrokade1@gmail.com'
          npx gh-pages -d dist -u "anuragrokade <anuragrokade1@gmail.com>" -r https://anuragrokade:${{ secrets.GITHUB_TOKEN }}@github.com/anuragrokade/react-devops.git
